# Generated by Django 4.2.1 on 2023-06-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_seguros', '0006_asegurado_poliza_alter_asegurado_documento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificado',
        ),
    ]
